name: dururu
description: "A subsonic backed music player"

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_audio: ^0.9.42
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner:
  riverpod_generator: ^2.6.2

flutter:
  uses-material-design: true
