name: dururu
description: "A subsonic backed music player"

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_audio: ^0.9.42
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.6.0
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  crypto: ^3.0.6
  flutter_riverpod: ^2.6.1
  animated_snack_bar: ^0.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  percent_indicator: ^4.2.4
  just_audio_background: ^0.0.1-beta.14
  flutter_svg: ^2.0.16
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  xml: ^6.5.0
  html: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/
